/*Sample Equipment Creator 

This simple console application demonstrates using the Intelligent InSites Web 
Services API to create new equipment from data entered into a command line. 
This class implements the BasicClient class to perform HTTP requests.*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.XPath;
using System.IO;
using System.Net;

namespace IntelligentInSites.CodeSamples {
    class EquipmentCreator {
        static void Main(string[] args) {
            BasicClient client = new BasicClient("http://insites-dev.intelligentinsites.com", "username", "password");

            //Get the required parameters from user
            Console.Write("name <IV Pole>: ");
            string name = Console.ReadLine().Trim();

            Console.Write("short-name <iv1>: ");
            string shortName = Console.ReadLine().Trim();

            Console.Write("type <Bxc6t>: ");
            string type = Console.ReadLine().Trim();

            Console.Write("status <Bxc>: ");
            string status = Console.ReadLine().Trim();

            Console.Write("service-status <Bxc>: ");
            string serviceStatus = Console.ReadLine().Trim();

            //Perform a POST request to create a resource
            ApiResponse createResponse = client.Post("/api/2.0/rest/equipment.xml", String.Format("name={0}&shortName={1}&type={2}&status={3}&service-status={4}", name, shortName, type, status, serviceStatus));
            Console.WriteLine("\nThe web service responded with:");
            Console.WriteLine(createResponse.ResponseData);

            //Parse the response to get the id of the new equipment
            String equipmentId = ParseEquipmentIdFromXMLResponse(createResponse);
            Console.WriteLine("Parsed the id from the response. The id is: " + equipmentId);

            //Assign a sensor to the equipment by using the take-sensor method. Sensor resources are identified by 
            //two fields, a key (the 'provider' field), and a value (the 'label' field).
            Console.WriteLine("\nAssigning an existing sensor to our new equipment...");
            Console.Write("sensor to assign <your-rtls.6025> ");    //provider.label
            String sensorId = Console.ReadLine().Trim();

            Dictionary<string, object> assignParams = new Dictionary<string, object>();
            assignParams["sensor"] = sensorId;
            ApiResponse assignResponse = client.Post("/api/2.0/rest/equipment/"+equipmentId+"/take-sensor.xml", assignParams);
            Console.WriteLine("\nAssigned a sensor to the new equipment. The web service responded with:");
            Console.WriteLine(assignResponse.ResponseData);

            Console.WriteLine("\nPress any key to quit");
            Console.Read();
        }

        /// <summary>
        /// Parses an InSites success HTTP response, and finds the ID of a newly created equipment resource. The response format must be XML.
        /// </summary>
        /// <param name="success">An <c>ApiResponse</c> representing an InSites XML response. The type of response required is one generated by the API call: POST /api/2.0/rest/equipment.xml.</param>
        /// <returns>The ID of the created equipment.</returns>
        public static string ParseEquipmentIdFromXMLResponse(ApiResponse response) {
            byte[] bytes = Encoding.ASCII.GetBytes(response.ResponseData);
            XmlTextReader reader = new XmlTextReader(new MemoryStream(bytes));
            try {
                while (reader.Read()) {
                    if (reader.NodeType == XmlNodeType.Element) {
                        if (reader.Name == "value") {
                            return reader.GetAttribute("id");
                        }
                    }
                }
            }
            catch (Exception e) {
                throw new Exception("Equipment ID not found", e);
            }
            finally {
                reader.Close();
            }
            throw new Exception("Equipment ID not found");
        }
    }
}
